spring:
  application:
    name: ibkr_xmlFileDownloader

server:
  port: ${PORT:8080}

ibkr:
  flex:
    token: ${ibkr_flex_token}
    query:
      id: ${ibkr_flex_query_id}

flex:
  query:
    bucket: portfolio_tracker_data
    filename: current/transactions.xml